const {levenshtein} = require('./levenshtein');

/**
 * Contains all the prices that are known to us
 */
const prices = {
    "padded": "5 gp",
    "padded-armor": "5 gp",
    "leather": "10 gp",
    "leather-armor": "10 gp",
    "studded-leather": "45 gp",
    "studded-leather-armor": "45 gp",
    "hide-armor": "10 gp",
    "chain-shirt": "50 gp",
    "scale-mail": "50 gp",
    "scale-mail-armor": "50 gp",
    "breastplate": "400 gp",
    "half-plate": "750 gp",
    "half-plate=armor": "750 gp",
    "ring-mail": "30 gp",
    "ring-mail-armor": "30 gp",
    "chain-mail": "75 gp",
    "chain-mail-armor": "75 gp",
    "splint": "200 gp",
    "splint-armor": "200 gp",
    "plate": "1,500 gp",
    "plate-armor": "1,500 gp",
    "shield": "10 gp",
    "club": "1 sp",
    "dagger": "2 gp",
    "greatclub": "2 sp",
    "handaxe": "5 gp",
    "javelin": "5 sp",
    "light-hammer": "2 gp",
    "mace": "5 gp",
    "quarterstaff": "2 sp",
    "sickle": "1 gp",
    "spear": "1 gp",
    "light-crossbow": "25 gp",
    "dart": "5 cp",
    "shortbow": "25 gp",
    "sling": "1 sp",
    "battleaxe": "10 gp",
    "flail": "10 gp",
    "glaive": "20 gp",
    "greataxe": "30 gp",
    "greatsword": "50 gp",
    "halberd": "20 gp",
    "lance": "10 gp",
    "longsword": "15 gp",
    "maul": "10 gp",
    "morningstar": "15 gp",
    "pike": "5 gp",
    "rapier": "25 gp",
    "scimitar": "25 gp",
    "shortsword": "10 gp",
    "trident": "5 gp",
    "war-pick": "5 gp",
    "warhammer": "15 gp",
    "whip": "2 gp",
    "blowgun": "10 gp",
    "hand-crossbow": "75 gp",
    "heavy-crossbow": "50 gp",
    "longbow": "50 gp",
    "net": "1 gp",
    "alchemists-supplies": "50 gp",
    "brewers-supplies": "20 gp",
    "calligraphers-supplies": "10 gp",
    "carpenters-tools": "8 gp",
    "cartographers-tools": "15 gp.",
    "cobblers-tools": "5 gp",
    "cooks-utensils": "1 gp",
    "glassblowers-tools": "30 gp",
    "jewelers-tools": "25 gp",
    "leatherworkers-tools": "5 gp",
    "masons-tools": "10 gp",
    "painters-supplies": "10 gp",
    "potters-tools": "10 gp",
    "smiths-tools": "20 gp",
    "tinkers-tools": "50 gp",
    "weavers-tools": "1 gp",
    "woodcarvers-tools": "1 gp",
    "dice-set": "1 sp",
    "dragonchess-set": "1 gp",
    "playing-card-set": "5 sp",
    "three-dragon-ante-set": "1 gp",
    "herbalism-kit": "5 gp",
    "bagpipes": "30 gp",
    "drum": "6 gp",
    "dulcimer": "25 gp",
    "flute": "2 gp",
    "lute": "35 gp",
    "lyre": "30 gp",
    "horn": "3 gp",
    "pan-flute": "12 gp",
    "shawm": "2 gp",
    "viol": "30 gp",
    "poisoners-kit": "50 gp",
    "thieves'-tools": "25 gp",
    "disguise-kit": "25 gp",
    "forgery-kit": "15 gp",
    "abacus": "2 gp",
    "acid": "25 gp",
    "vial-of-acid": "25 gp",
    "acid-vial": "25 gp",
    "alchemists-fire": "50 gp (flask)",
    "arrows": "1 gp (20pcs)",
    "blowgun-needles": "1 gp (50pcs)",
    "crossbow-bolts": "1 gp (20pcs)",
    "sling-bullets": "4 cp (20pcs)",
    "antitoxin": "50 gp (vial)",
    "crystal": "10 gp",
    "orb": "20 gp",
    "rod": "10 gp",
    "staff": "5 gp",
    "wand": "10 gp",
    "backpack": "2 gp",
    "ball-bearings": "1 gp (1,000pcs)",
    "barrel": "2 gp",
    "basket": "4 sp",
    "bedroll": "1 gp",
    "bell": "1 gp",
    "blanket": "5 sp",
    "block-and-tackle": "1 gp",
    "book": "25 gp",
    "glass-bottle": "2 gp",
    "bucket": "5 cp",
    "caltrops": "1 gp (20pcs)",
    "candle": "1 cp",
    "crossbow-case-bolt": "1 gp",
    "map-case-or-scroll": "1 gp",
    "chain": "5 gp (10ft.)",
    "chalk": "1 cp (1pc)",
    "chest": "5 gp",
    "climbers-kit": "25 gp",
    "common-clothes": "5 sp",
    "costume-clothes": "5 gp",
    "fine-clothes": "15 gp",
    "traveler-clothess": "2 gp",
    "component-pouch": "25 gp",
    "crowbar": "2 gp",
    "sprig-of-mistletoe": "1 gp",
    "mistletoe": "1 gp",
    "totem": "1 gp",
    "wooden-staff": "5 gp",
    "yew-wand": "10 gp",
    "fishing-tackle": "1 gp",
    "flask": "2 cp",
    "tankard": "2 cp",
    "grappling-hook": "2 gp",
    "hammer": "1 gp",
    "sledge-hammer": "2 gp",
    "healers-kit": "5 gp",
    "amulet": "5 gp",
    "emblem": "5 gp",
    "reliquary": "5 gp",
    "holy-water": "25 gp (flask)",
    "hourglass": "25 gp",
    "hunting-trap": "5 gp",
    "ink": "10 gp (1oz bottle)",
    "pen": "2 cp",
    "jug": "2 cp",
    "pitcher": "2 cp",
    "ladder": "1 sp (10ft.)",
    "lamp": "5 sp",
    "bullseye-lantern": "10 gp",
    "hooded-lantern": "5 gp",
    "lock": "10 gp",
    "magnifying-glass": "100 gp",
    "manacles": "2 gp",
    "mess-kit": "2 sp",
    "steel-mirror": "5 gp",
    "oil": "1 sp (flask)",
    "paper": "2 sp (1 sheet)",
    "parchment": "1 sp (1 sheet)",
    "perfume": "5 gp (vial)",
    "miner-picks": "2 gp",
    "piton": "5 cp",
    "basic-poison": "100 gp (vial)",
    "pole": "5 cp (10ft.)",
    "iron-pot": "2 gp",
    "potion-of-healing": "50 gp",
    "pouch": "5 sp",
    "quiver": "1 gp",
    "portable-ram": "4 gp",
    "rations": "5 sp (p/day)",
    "robes": "1 gp",
    "hempen-rope": "1 gp (50ft.)",
    "silk-rope": "10 gp (50ft.)",
    "rope": "1 gp (hempen, 50ft.) OR 10 gp (silk, 50ft.)",
    "sack": "1 cp",
    "merchant-scales": "5 gp",
    "scales": "5 gp",
    "sealing-wax": "5 sp",
    "shovel": "2 gp",
    "signal-whistle": "5 cp",
    "whistle": "5 cp",
    "signet-ring": "5 gp",
    "soap": "2 cp",
    "spellbook": "50 gp",
    "iron-spikes": "1 gp (10pcs)",
    "spyglass": "1,000 gp",
    "tent": "2 gp (2 person)",
    "tinderbox": "5 sp",
    "torch": "1 cp",
    "vial": "1 gp",
    "waterskin": "2 sp",
    "whetstone": "1 cp",
    "camel": "50gp",
    "donkey": "8gp",
    "mule": "8gp",
    "elephant": "200gp",
    "draft-horse": "50gp",
    "riding-horse": "75gp",
    "mastiff": "25gp",
    "pony": "30gp",
    "warhorse": "400gp",
    "bit-and-bridle": "2gp",
    "carriage": "100gp",
    "cart": "15gp",
    "chariot": "250gp",
    "feed": "5cp (per-day)",
    "pack": "5gp",
    "saddlebags": "4gp",
    "sled": "20gp",
    "wagon": "35gp",
    "galley": "30,000gp",
    "keelboat": "3,000gp",
    "longship": "10,000gp",
    "rowboat": "50gp",
    "sailing-ship": "10,000gp",
    "warship": "25,000gp",
}

/**
 * See if there is a price known for the provided itemName
 * @param {String} itemName 
 * @param {Boolean} verbal if it needs to print to the console
 */
exports.price = function(itemName, verbal){
    //Remove any weird characters
    item = itemName.replace("'s", 's');
    item = item.toLowerCase().trim().replace(/\s+/g, '-');
    //Try to retrieve the result from the price table
    let result = prices[item];
    //See if the item is plural
    let plural = item.substring(item.length - 1) == 's';
    //See if the item starts with a vowel
    let vowelStart = ["a", "e", "i", "o", "u"].indexOf(item.substring(0, 1)) > -1;
    //If we're verbal, print the output
    if(verbal){
        if(result){
            console.log((plural ? "" : (vowelStart ? "an " : "a ")) + item + " cost" + (plural ? " " : "s ") + result);
        }else{
            //Not found, try to look for closest match
            console.log("I couldn't find '" + itemName + "' in the database...");
            let keys = Object.keys(prices);
            /**Sort based on levenshtein order */
            keys.sort(function(a, b){
                return levenshtein(a, item) - levenshtein(b, item);
            });
            //Show the 5 best options
            console.log("--------------------------------");
            console.log("Closest options: " + keys.splice(0, 5).join(", "));
        }
    }
    //Return the found price anyway
    return result;
}